baseURL = "https://kaliban2056.github.io/"
languageCode = "en-us"
title = "Kaliban's Blog"
theme = "PaperMod"

paginate = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Kaliban's Blog"
description = "Cyber Security | Development | Self Hosting"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Kaliban"
images = [ "link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "/images/favicon.svg"
  favicon16x16 = "/images/favicon-16x16.svg"
  favicon32x32 = "/images/favicon-32x32.svg"

  [params.label]
  text = "Kaliban's Blog"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.homeInfoParams]
  Title = "Hello visitor!"
  Content = "Welcome to my corner of the interner, journey with me through the realms of tech, security, and programming innovation."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/kaliban2056"

   [[params.socialIcons]]
  name = "discord"
  url = "https://discordapp.com/users/509268181509079072"

  [[params.socialIcons]]
  name = "matrix"
  url = "https://matrix.to/#/@kaliban_205:matrix.org"

 [[params.socialIcons]]
  name = "buymeacoffee"
  url = "https://buymeacoffee.com"
  
  [[params.socialIcons]]
  name = "monero"
  url = ""

  [[params.socialIcons]]
  name = "bitcoin"
  url = ""

  [[params.socialIcons]]
  name = "pgp"
  url = ""

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 30

[markup.highlight]
noClasses = false
